[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci --include=dev"]

[build.nixpacksPlan.phases.build]
cmds = ["npm run build"]

[deploy]
startCommand = "node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
