[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.install]
cmds = ["npm install --include=dev"]

[build.nixpacksPlan.phases.build]
cmds = ["npm run build"]

[deploy]
startCommand = "node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
